release:
  prerelease: true

builds:
  - binary: rebashvc
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.buildTime={{.Date}}`.

archive:
  format: tar.gz

fpm:
  license: MIT
  homepage: https://github.com/sottey/rebashvc/
  formats:
    - deb
    - rpm

brew:
  github:
    owner: sottey
    name: homebrew-rebashvc
